<a href="https://colab.research.google.com/github/mohithsairamreddy/AI-Amrita/blob/master/Numpy/NumpTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy

In [ ]:
import numpy as np

Create array in np to use in python list

In [ ]:
mylist=[1,2,3,4,5]
print(mylist)

[1, 2, 3, 4, 5]


To convert python list to Numpy array

In [ ]:
numpy_array=np.array(mylist)
numpy_array

array([1, 2, 3, 4, 5])

In [ ]:
a  = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Addition to array

In [ ]:
m=numpy_array+10
print(m)

[11 12 13 14 15]


Shape of Array

In [ ]:
m=np.array([1,2,3,4])
print(m.shape)

(4,)


Example1 of data shape of array(two deminsional)

In [ ]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


Example2 of data shape of array(three deminsional)

In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

(2, 3)


In [ ]:
Data type of array

In [ ]:
m=np.array([1,2,3,4])
print(m.dtype)

int64


Null matrix 

In [ ]:
import numpy as np
x=np.zeros((3,3), dtype=np.int16,order='C')
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Reshaping Data

In [ ]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)


[[1 2 3]
 [4 5 6]]


In [ ]:
e.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Flatten Array

In [ ]:
m  = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
m.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

horizontal Append

In [ ]:
import numpy as np
m =np.array([1,2,3])
n =np.array([4,5,6])
o =np.array([7,8,9])

print( np.hstack((m,n,o)))

[1 2 3 4 5 6 7 8 9]


Vertical Append

In [ ]:
import numpy as np
m =np.array([1,2,3])
n =np.array([4,5,6])
o =np.array([7,8,9])

print( np.vstack((m,n,o)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Generating random numbers


```
# numpy.random.normal(loc, scale, size)
```




In [ ]:
random_array = np.random.normal(8,3.5,10)
print(random_array)	

[ 4.17781749 11.66247861 10.12629478  7.54893448  3.44162796 14.26436693
  5.11815234 10.56964805  9.48110739 13.22637237]


Generating a array in a sequence

In [ ]:
np.arange(15,25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Generating array in sequence with a deviation


```
numpy.arange(start, stop,deviation)
```



In [ ]:
np.arange(15,35,3)	

array([15, 18, 21, 24, 27, 30, 33])

Line spaces

In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

Log Space

In [ ]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

Slicing

In [ ]:
import numpy as np
print(m)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Acessing according to rows

In [ ]:
print('First row:',m[0])
print('Third row:',m[2])

First row: [1 2 3]
Third row: [7 8 9]


Acessing according to Columns

In [ ]:
print('First Column:',m[:,0])
print('Third Column:',m[:,2])

First Column: [ 1  4  7 10]
Third Column: [ 3  6  9 12]


Acessing two n values in a rows

In [ ]:
print(m[1, :2])

[4 5]


Acessing two values in Column

In [ ]:
print(m[:2,1])

[2 5]


Minimun,Maximum,Mean,Median,Standard Deviation

In [ ]:
import numpy as np
normal_array =np.random.normal(8,3.5,10)
print(normal_array)	

[11.82897476  2.77887255  4.42233318  8.31879167  5.24921454  4.88491225
  8.25069014  5.2785093   7.56399447  7.22864051]


In [ ]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

2.7788725519329045
11.828974763725553
6.580493337415295
6.253574902763659
2.45351995614224


Dot Product

In [ ]:
f=np.array([1,2])
g=np.array([7,8])
np.dot(f,g)

23

Matrix multiplication


In [ ]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

Inverse of Matrix

In [ ]:
E= np.array([(1,2), (4,5)])
print(np.linalg.inv(E))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


Detrminant of Matrix

In [ ]:
E= np.array([(1,2), (4,5)])
print(np.linalg.det(E))


-2.9999999999999996


Detrminant of Matrix in Integer

In [ ]:
E= np.array([(1,2), (4,5)])
print(int(np.linalg.det(E)))

-2


Rank of Matrix

In [ ]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
np.linalg.matrix_rank(mx)

3

Eigenvectors And Eigenvalue

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


 diagonal of a matrix

In [ ]:
gfg = np.matrix('[6, 2; 3, 4]')
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


Matrix transpose

In [ ]:
gfg = np.matrix('[4, 1; 12, 3]')
trans = gfg.transpose() 
print(trans)

[[ 4 12]
 [ 1  3]]


Trace of a matrix

In [ ]:
gfg = np.matrix('[4, 1; 12, 3]')
tracem = gfg.trace()
print(tracem)

[[7]]
