<a href="https://colab.research.google.com/github/mohithsairamreddy/AI-Amrita/blob/master/Numpy/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy Library

In [ ]:
import numpy as np

**Basics**

Initialization of 1-D Matrix

In [ ]:
a=np.array([1,2,3,4,5],dtype='int16')
print(a)

[1 2 3 4 5]


Initialization of 2-D Matrix

In [ ]:
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


Dimenison of Matrix

In [ ]:
a.ndim


1

In [ ]:
b.ndim

2

Shape of Matrix

In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(2, 4)

Data Type of Matrix

In [ ]:
a.dtype

dtype('int16')

In [ ]:
b.dtype

dtype('int64')

Size of each item in Matrix

In [ ]:
a.itemsize

2

Total Size of an Matrix

In [ ]:
#a.size *a.itemsize
a.nbytes

10

**Accessing/Changing specific elements, rows, columns, etc**

Indexing an element from Matrix

In [ ]:
b[1,3]

7

In [ ]:
b[1,-3]

5

Indexing a specific row and a specific coloumn

In [ ]:
b[0, :]

array([1, 2, 3, 4])

In [ ]:
b[: ,0]

array([1, 4])

Updating an Matrix

In [ ]:
b[1,3]=45
print(b)

[[ 1  2  3  4]
 [ 4  5  6 45]]


In [ ]:
b[: ,2]=66
print(b)

[[ 1  2 66  4]
 [ 4  5 66 45]]


**Initializing Different Types of Arrays**

Initialization of zero Matrix

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((3,1,5))

array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]])

Initialization of one's Matrix

In [ ]:
np.ones((3,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

Initialization of Indentitiy matrix

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Repeating a matrix

In [ ]:
arr =np.array([[5,6,7]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[5 5 5 6 6 6 7 7 7]]


Random Matrix(**float**) with given shape

In [ ]:
np.random.rand(2,3)

array([[0.47707532, 0.9911827 , 0.84828844],
       [0.92007149, 0.96386807, 0.07999317]])

Random Matrix(**int**) with given shape

In [ ]:
np.random.randint(100,size=(3,3))

array([[58,  5, 47],
       [22, 69,  6],
       [40, 78, 95]])

Initialiazation of Matrix with unique number

In [ ]:
np.full((2,2),56,dtype="int16")

array([[56, 56],
       [56, 56]], dtype=int16)

Copying a Matrix

In [ ]:
b=np.array([4,5,6])
a=b.copy()
print(a)


[4 5 6]


**Mathematics**

In [ ]:
a=np.array([4,5,6,7])
b=np.array([1,2,3,4])
print(a)
print(b)

[4 5 6 7]
[1 2 3 4]


Addition

In [ ]:
a+2

array([6, 7, 8, 9])

In [ ]:
a+b

array([ 5,  7,  9, 11])

Subraction

In [ ]:
a-2

array([2, 3, 4, 5])

In [ ]:
a-b

array([3, 3, 3, 3])

Multiplication

In [ ]:
a*2

array([ 8, 10, 12, 14])

In [ ]:
a*b

array([ 4, 10, 18, 28])

Division

In [ ]:
a/2

array([2. , 2.5, 3. , 3.5])

In [ ]:
a/b

array([4.  , 2.5 , 2.  , 1.75])

Power

In [ ]:
a**3

array([ 64, 125, 216, 343])

**Linear Algebra**

Matrix multiplication

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

Determinant of Matrix

In [ ]:
a=np.identity(5)
np.linalg.det(a)

1.0

Trace of Matrix

Inverse of Matrix